/**
 * @file static_list.h
 * @brief Static linked list implementation using array-based pool
 * 
 * This header provides a memory-efficient static linked list implementation
 * that uses a pre-allocated array pool. The implementation maintains two
 * linked lists: an active list for used nodes and a free list for available
 * nodes. This design eliminates dynamic memory allocation and provides
 * predictable memory usage for embedded systems.
 * 
 * Features:
 * - Fixed-size node pool allocated at compile time
 * - O(1) node allocation and deallocation
 * - Iterator macros for safe traversal
 * - Type-safe implementation using macros
 * 
 * @author developer
 * @date 2025
 */

#ifndef STATIC_LIST_H
#define STATIC_LIST_H

#include <stdint.h> 

// ============================================================================
// Constants
// ============================================================================

/** @brief Null index value indicating end of list or invalid node */
#define SLIST_NULL (-1)

// ============================================================================
// Type Definitions
// ============================================================================

/**
 * @brief Define a static list node structure
 * @param data_type The data type to store in each node
 * 
 * Creates a node structure containing:
 * - next: Index to the next node in the list (or SLIST_NULL)
 * - data: The user data of the specified type
 * 
 * This macro generates a struct type for list nodes.
 */
#define SLIST_NODE_T(data_type) \
    struct { \
        int next; \
        data_type data; \
    }

/**
 * @brief Define a static list structure
 * @param node_type The node type (typically generated by SLIST_NODE_T)
 * 
 * Creates a list structure containing:
 * - nodes: Pointer to the static array pool
 * - head: Index of the first node in the active list
 * - tail: Index of the last node in the active list
 * - free_head: Index of the first available node in the free list
 * - size: Number of nodes currently in use
 * - max_size: Total size of the node pool
 * 
 * This macro generates a struct type for the list container.
 */
#define SLIST_T(node_type) \
    struct { \
        node_type *nodes;    /**< Pointer to the static array (pool) */ \
        int head;            /**< Index of the first node (active list) */ \
        int tail;            /**< Index of the last node (active list) */ \
        int free_head;       /**< Index of the first available node (free list) */ \
        int size;            /**< Number of nodes currently in use */ \
        int max_size;        /**< Total size of the node pool */ \
    }

// ============================================================================
// List Definition and Initialization
// ============================================================================

/**
 * @brief Define a static list with node pool and types
 * @param list_name Base name for the list (used to generate type names)
 * @param data_type Data type to store in each node
 * @param max_size Maximum number of nodes in the pool
 * 
 * This macro:
 * - Creates node type: list_name##_node_t
 * - Creates list type: list_name##_t
 * - Allocates static pool: list_name##_pool[max_size]
 * - Declares list instance: list_name
 * 
 * Example:
 * @code
 * SLIST_DEFINE(my_list, int, 10);  // Creates my_list_node_t, my_list_t, etc.
 * @endcode
 */
#define SLIST_DEFINE(list_name, data_type, max_size) \
    typedef SLIST_NODE_T(data_type) list_name##_node_t; \
    typedef SLIST_T(list_name##_node_t) list_name##_t; \
    static list_name##_node_t list_name##_pool[(max_size)]; \
    static list_name##_t list_name;

/**
 * @brief Initialize a static list
 * @param list_name Name of the list instance to initialize
 * 
 * Initializes the list structure and sets up the free list chain.
 * All nodes are initially placed in the free list, and the active
 * list is empty. Must be called before using the list.
 * 
 * Example:
 * @code
 * SLIST_DEFINE(my_list, int, 10);
 * SLIST_INIT(my_list);
 * @endcode
 */
#define SLIST_INIT(list_name) \
    do { \
        (list_name).nodes = list_name##_pool; \
        (list_name).max_size = sizeof(list_name##_pool) / sizeof(list_name##_node_t); \
        (list_name).head = SLIST_NULL; \
        (list_name).tail = SLIST_NULL; \
        (list_name).size = 0; \
        \
        if ((list_name).max_size > 0) { \
            for (int i = 0; i < (list_name).max_size - 1; ++i) { \
                (list_name).nodes[i].next = i + 1; \
            } \
            (list_name).nodes[(list_name).max_size - 1].next = SLIST_NULL; \
            (list_name).free_head = 0; \
        } else { \
            (list_name).free_head = SLIST_NULL; \
        } \
    } while(0)

// ============================================================================
// Internal Helper Macros (not for direct use)
// ============================================================================

/**
 * @brief Allocate a node from the free list
 * @param list_ptr Pointer to the list structure
 * @return Index of allocated node, or SLIST_NULL if pool is exhausted
 * 
 * @internal
 * Removes a node from the free list and returns its index.
 * This is an internal macro used by other list operations.
 */
#define _SLIST_ALLOC_NODE(list_ptr) \
    ({ \
        int node_idx = SLIST_NULL; \
        if ((list_ptr)->free_head != SLIST_NULL) { \
            node_idx = (list_ptr)->free_head; \
            (list_ptr)->free_head = (list_ptr)->nodes[node_idx].next; \
        } \
        node_idx; \
    })

/**
 * @brief Free a node back to the free list
 * @param list_ptr Pointer to the list structure
 * @param node_idx Index of the node to free
 * 
 * @internal
 * Returns a node to the free list for reuse.
 * This is an internal macro used by other list operations.
 */
#define _SLIST_FREE_NODE(list_ptr, node_idx) \
    do { \
        if (node_idx >= 0 && node_idx < (list_ptr)->max_size) { \
            (list_ptr)->nodes[node_idx].next = (list_ptr)->free_head; \
            (list_ptr)->free_head = node_idx; \
        } \
    } while(0)

// ============================================================================
// Accessor Macros
// ============================================================================

/**
 * @brief Get pointer to data stored in a node
 * @param list_ptr Pointer to the list structure
 * @param idx Index of the node
 * @return Pointer to the data field of the specified node
 * 
 * Example:
 * @code
 * int *data = SLIST_GET_DATA(&my_list, node_idx);
 * *data = 42;
 * @endcode
 */
#define SLIST_GET_DATA(list_ptr, idx) \
    (&((list_ptr)->nodes[idx].data))

/**
 * @brief Get the index of the first node in the list
 * @param list_ptr Pointer to the list structure
 * @return Index of head node, or SLIST_NULL if list is empty
 */
#define SLIST_HEAD_IDX(list_ptr) \
    ((list_ptr)->head)

/**
 * @brief Get the index of the next node
 * @param list_ptr Pointer to the list structure
 * @param idx Index of the current node
 * @return Index of next node, or SLIST_NULL if current node is the last
 */
#define SLIST_NEXT_IDX(list_ptr, idx) \
    ((list_ptr)->nodes[idx].next)

/**
 * @brief Check if the list is empty
 * @param list_ptr Pointer to the list structure
 * @return Non-zero if list is empty, zero otherwise
 * 
 * Example:
 * @code
 * if (!SLIST_IS_EMPTY(&my_list)) {
 *     // Process list
 * }
 * @endcode
 */
#define SLIST_IS_EMPTY(list_ptr) \
    ((list_ptr)->head == SLIST_NULL)

/**
 * @brief Get the number of nodes currently in use
 * @param list_ptr Pointer to the list structure
 * @return Number of active nodes in the list
 */
#define SLIST_SIZE(list_ptr) \
    ((list_ptr)->size)

// ============================================================================
// Iterator Macros
// ============================================================================

/**
 * @brief Iterate through all nodes in the list
 * @param idx_var Variable name for the current node index (will be declared as int)
 * @param list_ptr Pointer to the list structure
 * 
 * Provides a for-loop iterator that traverses the list from head to tail.
 * The loop variable is the node index, which can be used with SLIST_GET_DATA.
 * 
 * Example:
 * @code
 * SLIST_FOREACH(idx, &my_list) {
 *     int *data = SLIST_GET_DATA(&my_list, idx);
 *     printf("Value: %d\n", *data);
 * }
 * @endcode
 */
#define SLIST_FOREACH(idx_var, list_ptr) \
    for (int idx_var = SLIST_HEAD_IDX(list_ptr); \
         idx_var != SLIST_NULL; \
         idx_var = SLIST_NEXT_IDX(list_ptr, idx_var))

/**
 * @brief Iterate through all nodes in the list (safe for deletion)
 * @param idx_var Variable name for the current node index (will be declared as int)
 * @param next_idx_var Variable name for the next node index (will be declared as int)
 * @param list_ptr Pointer to the list structure
 * 
 * Provides a for-loop iterator that safely traverses the list even when
 * nodes may be removed during iteration. The next index is cached before
 * processing the current node, allowing safe deletion.
 * 
 * Example:
 * @code
 * SLIST_FOREACH_SAFE(idx, next_idx, &my_list) {
 *     int *data = SLIST_GET_DATA(&my_list, idx);
 *     if (should_remove(*data)) {
 *         SLIST_REMOVE_CURRENT(&my_list, idx, prev_idx);
 *     } else {
 *         prev_idx = idx;
 *     }
 * }
 * @endcode
 */
#define SLIST_FOREACH_SAFE(idx_var, next_idx_var, list_ptr) \
    for (int idx_var = SLIST_HEAD_IDX(list_ptr), next_idx_var = (idx_var == SLIST_NULL ? SLIST_NULL : SLIST_NEXT_IDX(list_ptr, idx_var)); \
         idx_var != SLIST_NULL; \
         idx_var = next_idx_var, next_idx_var = (idx_var == SLIST_NULL ? SLIST_NULL : SLIST_NEXT_IDX(list_ptr, idx_var)))

// ============================================================================
// List Operations
// ============================================================================

/**
 * @brief Link a new node to the tail of the list
 * @param list_ptr Pointer to the list structure
 * @param new_idx Index of the node to append
 * 
 * @internal
 * Appends a node to the end of the active list and updates the tail pointer.
 * This is an internal macro used by other list operations.
 */
#define _SLIST_LINK_TAIL(list_ptr, new_idx) \
    do { \
        (list_ptr)->nodes[new_idx].next = SLIST_NULL; \
        if ((list_ptr)->tail == SLIST_NULL) { /* List was empty */ \
            (list_ptr)->head = new_idx; \
            (list_ptr)->tail = new_idx; \
        } else { \
            (list_ptr)->nodes[(list_ptr)->tail].next = new_idx; \
            (list_ptr)->tail = new_idx; \
        } \
        (list_ptr)->size++; \
    } while(0)

/**
 * @brief Remove a node from the list
 * @param list_ptr Pointer to the list structure
 * @param current_idx Index of the node to remove
 * @param prev_idx Index of the previous node (SLIST_NULL if removing head)
 * 
 * Removes the specified node from the active list and returns it to the
 * free list. Updates head/tail pointers as necessary. The node's data
 * is not cleared, so ensure it's no longer needed before removal.
 * 
 * This macro should be used with SLIST_FOREACH_SAFE when removing nodes
 * during iteration. When not iterating, you need to track the previous
 * node index manually.
 * 
 * Example:
 * @code
 * int prev_idx = SLIST_NULL;
 * SLIST_FOREACH_SAFE(idx, next_idx, &my_list) {
 *     int *data = SLIST_GET_DATA(&my_list, idx);
 *     if (should_remove(*data)) {
 *         SLIST_REMOVE_CURRENT(&my_list, idx, prev_idx);
 *     } else {
 *         prev_idx = idx;
 *     }
 * }
 * @endcode
 */
#define SLIST_REMOVE_CURRENT(list_ptr, current_idx, prev_idx) \
    do { \
        if ((current_idx) == SLIST_NULL) break; \
        int next_idx = (list_ptr)->nodes[current_idx].next; \
        if ((prev_idx) == SLIST_NULL) { \
            (list_ptr)->head = next_idx; \
        } else { \
            (list_ptr)->nodes[prev_idx].next = next_idx; \
        } \
        if ((list_ptr)->tail == (current_idx)) { \
            (list_ptr)->tail = (prev_idx); \
        } \
        _SLIST_FREE_NODE(list_ptr, current_idx); \
        (list_ptr)->size--; \
    } while(0)

#endif // STATIC_LIST_H